import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { useRef } from "react";
import Test from "../Comonents/Test";
import { DndProvider } from "react-dnd";
import { HTML5Backend } from "react-dnd-html5-backend";
import Screenshort from "../Comonents/Screenshort";

const data = [
  {
    id: 1,
    name: "Learn",
    desc: "Find in-depth information about Next.js features and API.",
  },

  {
    id: 2,
    name: "Learn2",
    desc: "Find in-depth information about Next.js features and API.",
  },

  {
    id: 3,
    name: "Learn3",
    desc: "Find in-depth information about Next.js features and API.",
  },

  {
    id: 4,
    name: "Learn4",
    desc: "Find in-depth information about Next.js features and API.",
  },
];

export default function Home() {
  return (
    // <div className={styles.container}>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    //   <main className={styles.main}>
    //     <h1 className={styles.title}>
    //       Welcome to <a href="https://nextjs.org">Next.js!</a>
    //     </h1>
    //     <p className={styles.description}>
    //       Get started by editing{" "}
    //       <code className={styles.code}>pages/index.js</code>
    //     </p>{" "}
    //     <div className={styles.grid}>
    //       {data.map((data, i) => (
    //         <div className={styles.card} key={i}>
    //           <div ref={drag}>
    //             <h2>{data.name} &rarr;</h2>
    //             <p>{data.desc}</p>
    //           </div>
    //         </div>
    //       ))}
    //     </div>
    //   </main>

    //   <footer className={styles.footer}>
    //     <a
    //       href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //       target="_blank"
    //       rel="noopener noreferrer"
    //     >
    //       Powered by{" "}
    //       <span className={styles.logo}>
    //         <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
    //       </span>
    //     </a>
    //   </footer>
    // </div>
    <>
      <Screenshort
        url="https://bookworm-light-nextjs.vercel.app/"
        text="thmefisher"
      />

      <DndProvider backend={HTML5Backend}>
        {" "}
        <Test data={data} />
      </DndProvider>
    </>
  );
}
